<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BlazorAdmin.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.msbuild">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="bunit" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BlazorAdmin\BlazorAdmin.csproj" />
    <ProjectReference Include="..\..\src\BlazorShared\BlazorShared.csproj" />
  </ItemGroup>

</Project>
